/* eslint-disable  func-names */
/* eslint-disable max-len */
/* eslint quote-props: ['error', 'consistent']*/
module.exports = {
    'FLASHBOMBS_EN_US': {
            'kirin': 'inn normal, enraged and fatigued state the kirin is not vulnerable to flash bombs.',
            'oroshi kirin': 'inn normal, enraged and fatigued state the oroshi kirin is not vulnerable to flash bombs.',
            'gypceros': 'inn normal, enraged and fatigued state the gypceros is not vulnerable to flash bombs.',
            'purple gypceros': 'inn normal, enraged and fatigued state the purple gypceros is not vulnerable to flash bombs.',
            'gore magala': 'inn normal, enraged and fatigued state the gore magala is not vulnerable to flash bombs.',
            'chaotic gore magala': 'inn normal, enraged and fatigued state the chaotic gore magala is not vulnerable to flash bombs.',
            'gogmazios': 'inn normal, enraged and fatigued state the gogmazios is not vulnerable to flash bombs.',
            'daimyo hermitaur': 'inn normal, enraged and fatigued state the daimyo hermitaur is not vulnerable to flash bombs.',
            'plum d.hermitaur': 'inn normal, enraged and fatigued state the plum d.hermitaur is not vulnerable to flash bombs.',
            'dalamadur': 'inn normal, enraged and fatigued state the dalamadur is not vulnerable to flash bombs.',
            'shah dalamadur': 'inn normal, enraged and fatigued state the shah dalamadur is not vulnerable to flash bombs.',
            'dah ren mohran': 'inn normal, enraged and fatigued state the dah ren mohran is not vulnerable to flash bombs.',
            'cephadrome': 'inn normal, enraged and fatigued state the cephadrome is not vulnerable to flash bombs.',
            'khezu': 'inn normal, enraged and fatigued state the khezu is not vulnerable to flash bombs.',
            'red khezu': 'inn normal, enraged and fatigued state the red khezu is not vulnerable to flash bombs.',
            'fatalis': 'inn normal, enraged and fatigued state the fatalis is not vulnerable to flash bombs.',
            'crimson fatalis': 'inn normal, enraged and fatigued state the crimson fatalis is not vulnerable to flash bombs.',
            'white fatalis': 'inn normal, enraged and fatigued state the white fatalis is not vulnerable to flash bombs.',
            'akantor': 'the akantor is  vulnerable to flash bombs in all three states.',
            'seltas': 'the seltas is  vulnerable to flash bombs in all three states.',
            'desert seltas': 'the desert seltas is  vulnerable to flash bombs in all three states.',
            'deviljho': 'the deviljho is  vulnerable to flash bombs in all three states.',
            'savage deviljho': 'the savage deviljho is  vulnerable to flash bombs in all three states.',
            'yian garuga': 'the yian garuga is  vulnerable to flash bombs in all three states.',
            'yian kut-ku': 'the yian kut-ku is  vulnerable to flash bombs in all three states.',
            'blue yian kut-ku': 'the blue yian kut-ku is  vulnerable to flash bombs in all three states.',
            'ukanlos': 'the ukanlos is  vulnerable to flash bombs in all three states.',
            'lagombi': 'the lagombi is  vulnerable to flash bombs in all three states.',
            'chameleos': 'the chameleos is  vulnerable to flash bombs in all three states.',
            'najarala': 'the najarala is  vulnerable to flash bombs in all three states.',
            'tidal najarala': 'the tidal najarala is  vulnerable to flash bombs in all three states.',
            'kushala daora': 'the kushala daora is  vulnerable to flash bombs in all three states.',
            'rusted kushala daora': 'the rusted kushala daora is  vulnerable to flash bombs in all three states.',
            'gravios': 'the gravios is  vulnerable to flash bombs in all three states.',
            'black gravios': 'the black gravios is  vulnerable to flash bombs in all three states.',
            'kecha wacha': 'the kecha wacha is  vulnerable to flash bombs in all three states.',
            'ash kecha wacha': 'the ash kecha wacha is  vulnerable to flash bombs in all three states.',
            'seltas queen': 'the seltas queen is  vulnerable to flash bombs in all three states.',
            'desert seltas queen': 'the desert seltas queen is  vulnerable to flash bombs in all three states.',
            'zamtrios': 'the zamtrios is  vulnerable to flash bombs in all three states.',
            'tigerstripe zamtrios': 'the tigerstripe zamtrios is  vulnerable to flash bombs in all three states.',
            'shagaru magala': 'the shagaru magala is  vulnerable to flash bombs in all three states.',
            'zinogre': 'the zinogre is  vulnerable to flash bombs in all three states.',
            'stygian zinogre': 'the stygian zinogre is  vulnerable to flash bombs in all three states.',
            'seregios': 'the seregios is  vulnerable to flash bombs in all three states.',
            'diablos': 'the diablos is  vulnerable to flash bombs in all three states.',
            'black diablos': 'the black diablos is  vulnerable to flash bombs in all three states.',
            'tigrex': 'the tigrex is  vulnerable to flash bombs in all three states.',
            'brute tigrex': 'the brute tigrex is  vulnerable to flash bombs in all three states.',
            'molten tigrex': 'the molten tigrex is  vulnerable to flash bombs in all three states.',
            'teostra': 'the teostra is  vulnerable to flash bombs in all three states.',
            'tetsucabra': 'the tetsucabra is  vulnerable to flash bombs in all three states.',
            'berserk tetsucabra': 'the berserk tetsucabra is  vulnerable to flash bombs in all three states.',
            'iodrome': 'the iodrome is  vulnerable to flash bombs in all three states.',
            'gendrome': 'the gendrome is  vulnerable to flash bombs in all three states.',
            'great jaggi': 'the great jaggi is  vulnerable to flash bombs in all three states.',
            'velocidrome': 'the velocidrome is  vulnerable to flash bombs in all three states.',
            'nerscylla': 'the nerscylla is  vulnerable to flash bombs in all three states.',
            'shrouded nerscylla': 'the shrouded nerscylla is  vulnerable to flash bombs in all three states.',
            'basarios': 'the basarios is  vulnerable to flash bombs in all three states.',
            'ruby basarios': 'the ruby basarios is  vulnerable to flash bombs in all three states.',
            'congalala': 'the congalala is  vulnerable to flash bombs in all three states.',
            'emerald congalala': 'the emerald congalala is  vulnerable to flash bombs in all three states.',
            'brachydios': 'the brachydios is  vulnerable to flash bombs in all three states.',
            'raging brachydios': 'the raging brachydios is  vulnerable to flash bombs in all three states.',
            'monoblos': 'the monoblos is  vulnerable to flash bombs in all three states.',
            'white monoblos': 'the white monoblos is  vulnerable to flash bombs in all three states.',
            'rajang': 'the rajang is  vulnerable to flash bombs in all three states.',
            'furious rajang': 'the furious rajang is  vulnerable to flash bombs in all three states.',
            'rathian': 'the rathian is  vulnerable to flash bombs in all three states.',
            'pink rathian': 'the pink rathian is  vulnerable to flash bombs in all three states.',
            'gold rathian': 'the gold rathian is  vulnerable to flash bombs in all three states.',
            'rathalos': 'the rathalos is  vulnerable to flash bombs in all three states.',
            'azure rathalos': 'the azure rathalos is  vulnerable to flash bombs in all three states.',
            'silver rathalos': 'the silver rathalos is  vulnerable to flash bombs in all three states.',

    },
};
