/* eslint-disable  func-names */
/* eslint-disable max-len */
/* eslint quote-props: ['error', 'consistent']*/
module.exports = {
    'PITFALLTRAPS_EN_US': {
        'akantor': 'in normal, enraged and fatigued state the akantor is not vulnerable to pitfall traps.',
        'ukanlos': 'in normal, enraged and fatigued state the ukanlos is not vulnerable to pitfall traps.',
        'chameleos': 'in normal, enraged and fatigued state the chameleos is not vulnerable to pitfall traps.',
        'kirin': 'in normal, enraged and fatigued state the kirin is not vulnerable to pitfall traps.',
        'oroshi kirin': 'in normal, enraged and fatigued state the oroshi kirin is not vulnerable to pitfall traps.',
        'kushala daora': 'in normal, enraged and fatigued state the kushala daora is not vulnerable to pitfall traps.',
        'rusted kushala daora': 'in normal, enraged and fatigued state the rusted kushala daora is not vulnerable to pitfall traps.',
        'gogmazios': 'in normal, enraged and fatigued state the gogmazios is not vulnerable to pitfall traps.',
        'shagaru magala': 'in normal, enraged and fatigued state the shagaru magala is not vulnerable to pitfall traps.',
        'dalamadur': 'in normal, enraged and fatigued state the dalamadur is not vulnerable to pitfall traps.',
        'shah dalamadur': 'in normal, enraged and fatigued state the shah dalamadur is not vulnerable to pitfall traps.',
        'dah ren mohran': 'in normal, enraged and fatigued state the dah ren mohran is not vulnerable to pitfall traps.',
        'teostra': 'in normal, enraged and fatigued state the teostra is not vulnerable to pitfall traps.',
        'raging brachydios': 'in normal, enraged and fatigued state the raging brachydios is not vulnerable to pitfall traps.',
        'fatalis': 'in normal, enraged and fatigued state the fatalis is not vulnerable to pitfall traps.',
        'crimson fatalis': 'in normal, enraged and fatigued state the crimson fatalis is not vulnerable to pitfall traps.',
        'white fatalis': 'in normal, enraged and fatigued state the white fatalis is not vulnerable to pitfall traps.',
        'seltas': 'in normal, enraged and fatigued state the seltas is not vulnerable to pitfall traps.',
        'desert seltas': 'in normal, enraged and fatigued state the desert seltas is not vulnerable to pitfall traps.',
        'deviljho': 'in normal, enraged and fatigued state the deviljho is not vulnerable to pitfall traps.',
        'savage deviljho': 'in normal, enraged and fatigued state the savage deviljho is not vulnerable to pitfall traps.',
        'yian kut-ku': 'in normal, enraged and fatigued state the yian kut-ku is not vulnerable to pitfall traps.',
        'blue yian kut-ku': 'in normal, enraged and fatigued state the blue yian kut-ku is not vulnerable to pitfall traps.',
        'lagombi': 'in normal, enraged and fatigued state the lagombi is not vulnerable to pitfall traps.',
        'najarala': 'in normal, enraged and fatigued state the najarala is not vulnerable to pitfall traps.',
        'tidal najarala': 'in normal, enraged and fatigued state the tidal najarala is not vulnerable to pitfall traps.',
        'gravios': 'in normal, enraged and fatigued state the gravios is not vulnerable to pitfall traps.',
        'black gravios': 'in normal, enraged and fatigued state the black gravios is not vulnerable to pitfall traps.',
        'kecha wacha': 'in normal, enraged and fatigued state the kecha wacha is not vulnerable to pitfall traps.',
        'ash kecha wacha': 'in normal, enraged and fatigued state the ash kecha wacha is not vulnerable to pitfall traps.',
        'seltas queen': 'in normal, enraged and fatigued state the seltas queen is not vulnerable to pitfall traps.',
        'desert seltas queen': 'in normal, enraged and fatigued state the desert seltas queen is not vulnerable to pitfall traps.',
        'gypceros': 'in normal, enraged and fatigued state the gypceros is not vulnerable to pitfall traps.',
        'purple gypceros': 'in normal, enraged and fatigued state the purple gypceros is not vulnerable to pitfall traps.',
        'gore magala': 'in normal, enraged and fatigued state the gore magala is not vulnerable to pitfall traps.',
        'chaotic gore magala': 'in normal, enraged and fatigued state the chaotic gore magala is not vulnerable to pitfall traps.',
        'zamtrios': 'in normal, enraged and fatigued state the zamtrios is not vulnerable to pitfall traps.',
        'tigerstripe zamtrios': 'in normal, enraged and fatigued state the tigerstripe zamtrios is not vulnerable to pitfall traps.',
        'zinogre': 'in normal, enraged and fatigued state the zinogre is not vulnerable to pitfall traps.',
        'stygian zinogre': 'in normal, enraged and fatigued state the stygian zinogre is not vulnerable to pitfall traps.',
        'seregios': 'in normal, enraged and fatigued state the seregios is not vulnerable to pitfall traps.',
        'daimyo hermitaur': 'in normal, enraged and fatigued state the daimyo hermitaur is not vulnerable to pitfall traps.',
        'plum d.hermitaur': 'in normal, enraged and fatigued state the plum d.hermitaur is not vulnerable to pitfall traps.',
        'diablos': 'in normal, enraged and fatigued state the diablos is not vulnerable to pitfall traps.',
        'black diablos': 'in normal, enraged and fatigued state the black diablos is not vulnerable to pitfall traps.',
        'tigrex': 'in normal, enraged and fatigued state the tigrex is not vulnerable to pitfall traps.',
        'brute tigrex': 'in normal, enraged and fatigued state the brute tigrex is not vulnerable to pitfall traps.',
        'molten tigrex': 'in normal, enraged and fatigued state the molten tigrex is not vulnerable to pitfall traps.',
        'tetsucabra': 'in normal, enraged and fatigued state the tetsucabra is not vulnerable to pitfall traps.',
        'berserk tetsucabra': 'in normal, enraged and fatigued state the berserk tetsucabra is not vulnerable to pitfall traps.',
        'iodrome': 'in normal, enraged and fatigued state the iodrome is not vulnerable to pitfall traps.',
        'gendrome': 'in normal, enraged and fatigued state the gendrome is not vulnerable to pitfall traps.',
        'great jaggi': 'in normal, enraged and fatigued state the great jaggi is not vulnerable to pitfall traps.',
        'velocidrome': 'in normal, enraged and fatigued state the velocidrome is not vulnerable to pitfall traps.',
        'cephadrome': 'in normal, enraged and fatigued state the cephadrome is not vulnerable to pitfall traps.',
        'nerscylla': 'in normal, enraged and fatigued state the nerscylla is not vulnerable to pitfall traps.',
        'shrouded nerscylla': 'in normal, enraged and fatigued state the shrouded nerscylla is not vulnerable to pitfall traps.',
        'basarios': 'in normal, enraged and fatigued state the basarios is not vulnerable to pitfall traps.',
        'ruby basarios': 'in normal, enraged and fatigued state the ruby basarios is not vulnerable to pitfall traps.',
        'congalala': 'in normal, enraged and fatigued state the congalala is not vulnerable to pitfall traps.',
        'emerald congalala': 'in normal, enraged and fatigued state the emerald congalala is not vulnerable to pitfall traps.',
        'brachydios': 'in normal, enraged and fatigued state the brachydios is not vulnerable to pitfall traps.',
        'khezu': 'in normal, enraged and fatigued state the khezu is not vulnerable to pitfall traps.',
        'red khezu': 'in normal, enraged and fatigued state the red khezu is not vulnerable to pitfall traps.',
        'monoblos': 'in normal, enraged and fatigued state the monoblos is not vulnerable to pitfall traps.',
        'white monoblos': 'in normal, enraged and fatigued state the white monoblos is not vulnerable to pitfall traps.',
        'furious rajang': 'in normal, enraged and fatigued state the furious rajang is not vulnerable to pitfall traps.',
        'rathian': 'in normal, enraged and fatigued state the rathian is not vulnerable to pitfall traps.',
        'pink rathian': 'in normal, enraged and fatigued state the pink rathian is not vulnerable to pitfall traps.',
        'gold rathian': 'in normal, enraged and fatigued state the gold rathian is not vulnerable to pitfall traps.',
        'rathalos': 'in normal, enraged and fatigued state the rathalos is not vulnerable to pitfall traps.',
        'azure rathalos': 'in normal, enraged and fatigued state the azure rathalos is not vulnerable to pitfall traps.',
        'silver rathalos': 'in normal, enraged and fatigued state the silver rathalos is not vulnerable to pitfall traps.',
        'yian garuga': 'in normal and fatigued state the yian garuga is vulnerable to pitfall traps, but not when enraged.',
        'rajang': 'in normal and fatigued state the rajang is not vulnerable to pitfall traps, but is when enraged.',
    },
};
