/* eslint-disable  func-names */
/* eslint-disable max-len */
/* eslint quote-props: ['error', 'consistent']*/
module.exports = {
    'RECIPE_EN_US': {
        'potion': 'a potion can be crated by combining an herb and a blue mushroom.',
        'mega potion': 'a mega potion can be crated by combining a potion and honey.',
        'first aid med plus': 'a first-aid med+ can be crated by combining a first-aid med and honey.',
        'nutrients': 'nutrients can be crated by combining a  blue mushroom and a godbug.',
        'mega nutrients': 'mega nutrients can be crated by combining nutrients and honey.',
        'antidote': 'an antidote can be crated by combining an antidote herb and a blue mushroom.',
        'herbal medicine': 'herbal medicine can be crated by combining gloamgrass root and a bitterbug.',
        'max potion': 'a max potion can be crated by combining mega nutrients and a dragon toadstool.',
        'ancient potion': 'an ancient potion can be crated by combining immuniser and a kelbi horn.',
        'dust of life': 'dust of life can be crated by combining a kelbi horn and gloamgrass bud.',
        'catalyst': 'a catalyst can be crated by combining honey and a bitterbug.',
        'immuniser': 'immuniser can be crated by combining a catalyst and a dragon toadstool.',
        'cleanser': 'cleanser can be crated by combining a catalyst and a popfish.',
        'dash juice': 'dash juice can be crated by combining a catalyst and a rare steak.',
        'mega dash juice': 'mega dash juice can be crated by combining a well-done steak and a dash extract.',
        'energy drink': 'an energy drink can be crated by combining honey and a nitroshroom.',
        'energy drink': 'an energy drink can be crated by combining a hot pepper and a sleepyfish.',
        'demondrug': 'demondrug can be crated by combining a catalyst and a might seed.',
        'mega demondrug': 'mega demondrug can be crated by combining demondrug and a pale extract.',
        'might pill': 'a might pill can be crated by combining immuniser and a might seed.',
        'armourskin': 'armourskin can be crated by combining a catalyst and an adamant seed.',
        'mega armourskin': 'mega armourskin can be crated by combining armourskin and a pale extract.',
        'adamant pill': 'an adamant pill can be crated by combining immuniser and a adamant seed.',
        'hot drink': 'a hot drink can be crated by combining a hot pepper and a bitterbug.',
        'hot meat': 'hot meat can be crated by combining a well-done steak and a hot pepper.',
        'cool drink': 'a cool drink can be crated by combining an ice crystal and a bitterbug.',
        'chilled meat': 'chilled meat can be crated by combining a well-done steak and an ice crystal.',
        'frozen berry': 'a frozen berry can be crated by combining an ice crystal and a tropical berry.',
        'poisoned meat': 'poisoned meat can be crated by combining raw meat and a toadstool.',
        'tinged meat': 'tinged meat can be crated by combining raw meat and a parashroom.',
        'drugged meat': 'drugged meat can be crated by combining raw meat and a sleep herb.',
        'bomb casing': 'a bomb casing can be crated by combining a sap plant and stone.',
        'bomb casing': 'a bomb casing can be crated by combining a sap plant and an iron ore.',
        'deodorant': 'deodorant can be crated by combining a bomb casing and a bitterbug.',
        'smoke bomb': 'a smoke bomb can be crated by combining a bomb casing and an ivy.',
        'poison smoke bomb': 'a poison smoke bomb can be crated by combining a bomb casing and a toadstool.',
        'poison smoke bomb': 'a poison smoke bomb can be crated by combining a bomb casing and a poison sac.',
        'flash bomb': 'a flash bomb can be crated by combining a bomb casing and a flashbug.',
        'dung bomb': 'a dung bomb can be crated by combining a bomb casing and dung.',
        'paintball': 'a paintball can be crated by combining a sap plant and a paintberry.',
        'farcaster': 'farcaster can be crated by combining a bomb casing and an exciteshroom.',
        'gunpowder': 'gunpowder can be crated by combining a fire herb and a nitroshroom.',
        'small barrel bomb': 'a small barrel bomb can be crated by combining a small barrel and a fire herb.',
        'small barrel bomb plus': 'a small barrel bomb plus can be crated by combining a barrel bomb and a burst arowana.',
        'large barrel bomb': 'a large barrel bomb can be crated by combining gunpowder and a large barrel.',
        'large barrel bomb plus': 'a large barrel bomb plus can be crated by combining a large barrel bomb and a scatterfish.',
        'bounce bomb': 'a bounce bomb can be crated by combining a small barrel bomb and a bnahabra wing.',
        'bounce bomb plus': 'a bounce bomb plus can be crated by combining a bounce bomb and a bomb arowana.',
        'sonic bomb': 'a sonic bomb can be crated by combining gunpowder and a screamer sac.',
        'felvine bomb': 'a felvine bomb can be crated by combining a small barrel bomb and a felvine.',
        'net': 'a net can be crated by combining a spider web and an ivy.',
        'pitfall trap': 'a pitfall trap can be crated by combining a net and a trap tool.',
        'shock trap': 'a shock trap can be crated by combining a trap tool and a thunderbug.',
        'shock trap': 'a shock trap can be crated by combining a trap tool and a genprey fang.',
        'goldenfish bait': 'goldenfish bait can be crated by combining a mega fishing fly and a snakebee larva.',
        'sushifish bait': 'sushifish bait can be crated by combining a mega fishing fly and an insect husk.',
        'burst bait': 'burst bait can be crated by combining a mega fishing fly and a stinkhopper.',
        'old pickaxe': 'an old pickaxe can be crated by combining stone and a mystery bone.',
        'iron pickaxe': 'an iron pickaxe can be crated by combining an iron ore and a mystery bone.',
        'mega pickaxe': 'a mega pickaxe can be crated by combining a machalite ore and a mystery bone.',
        'old bug net': 'an old bug net can be crated by combining an ivy and a mystery bone.',
        'bug net': 'a bug net can be crated by combining an ivy and a small monster bone.',
        'mega bug net': 'a mega bug net can be crated by combining an ivey and a medium monster bone.',
        'lifecrystals': 'lifecrystals can be crated by combining a godbug and a wyvern fang.',
        'lifepowder': 'lifepowder can be crated by combining lifecrystals and a wyvern claw.',
        'health horn': 'a health horn can be crated by combining lifecrystals and a field horn.',
        'antidote horn': 'an antidote horn can be crated by combining an antidote and a field horn.',
        'demon horn': 'a demon horn can be crated by combining a mega demondrug and a medium monster bone.',
        'armour horn': 'an armour horn can be crated by combining a mega armourskin and a medium monster bone.',
        'poison knife': 'a poison knife can be crated by combining a throwing knife and a toadstool .',
        'sleep knife': 'a sleep knife can be crated by combining a throwing knife and a sleep herb.',
        'paralysis knife': 'a paralysis knife can be crated by combining a throwing knife and a parashroom.',
        'boomerang': 'a boomerang can be crated by combining a whetstone and a small monster bone.',
        'powertalon': 'a powertalon can be crated by combining a powercharm and a deviljho talon.',
        'armourtalon': 'a armourtalon can be crated by combining a armourcharm and a deviljho talon.',
    },
};
