/* eslint-disable  func-names */
/* eslint-disable max-len */
/* eslint quote-props: ['error', 'consistent']*/
module.exports = {
    'SHOCKTRAPS_EN_US': {
            'akantor': 'in normal, enraged and fatigued state the akantor is not vulnerable to shock traps.',
            'ukanlos': 'in normal, enraged and fatigued state the ukanlos is not vulnerable to shock traps.',
            'chameleos': 'in normal, enraged and fatigued state the chameleos is not vulnerable to shock traps.',
            'kirin': 'in normal, enraged and fatigued state the kirin is not vulnerable to shock traps.',
            'oroshi kirin': 'in normal, enraged and fatigued state the oroshi kirin is not vulnerable to shock traps.',
            'kushala daora': 'in normal, enraged and fatigued state the kushala daora is not vulnerable to shock traps.',
            'rusted kushala daora': 'in normal, enraged and fatigued state the rusted kushala daora is not vulnerable to shock traps.',
            'gypceros': 'in normal, enraged and fatigued state the gypceros is not vulnerable to shock traps.',
            'purple gypceros': 'in normal, enraged and fatigued state the purple gypceros is not vulnerable to shock traps.',
            'gogmazios': 'in normal, enraged and fatigued state the gogmazios is not vulnerable to shock traps.',
            'shagaru magala': 'in normal, enraged and fatigued state the shagaru magala is not vulnerable to shock traps.',
            'dalamadur': 'in normal, enraged and fatigued state the dalamadur is not vulnerable to shock traps.',
            'shah dalamadur': 'in normal, enraged and fatigued state the shah dalamadur is not vulnerable to shock traps.',
            'dah ren mohran': 'in normal, enraged and fatigued state the dah ren mohran is not vulnerable to shock traps.',
            'teostra': 'in normal, enraged and fatigued state the teostra is not vulnerable to shock traps.',
            'raging brachydios': 'in normal, enraged and fatigued state the raging brachydios is not vulnerable to shock traps.',
            'fatalis': 'in normal, enraged and fatigued state the fatalis is not vulnerable to shock traps.',
            'crimson fatalis': 'in normal, enraged and fatigued state the crimson fatalis is not vulnerable to shock traps.',
            'white fatalis': 'in normal, enraged and fatigued state the white fatalis is not vulnerable to shock traps.',
            'seltas': 'the seltas is vulnerable to shock traps in all three states.',
            'desert seltas': 'the desert seltas is vulnerable to shock traps in all three states.',
            'deviljho': 'the deviljho is vulnerable to shock traps in all three states.',
            'savage deviljho': 'the savage deviljho is vulnerable to shock traps in all three states.',
            'yian garuga': 'the yian garuga is vulnerable to shock traps in all three states.',
            'yian kut-ku': 'the yian kut-ku is vulnerable to shock traps in all three states.',
            'blue yian kut-ku': 'the blue yian kut-ku is vulnerable to shock traps in all three states.',
            'lagombi': 'the lagombi is vulnerable to shock traps in all three states.',
            'najarala': 'the najarala is vulnerable to shock traps in all three states.',
            'tidal najarala': 'the tidal najarala is vulnerable to shock traps in all three states.',
            'gravios': 'the gravios is vulnerable to shock traps in all three states.',
            'black gravios': 'the black gravios is vulnerable to shock traps in all three states.',
            'kecha wacha': 'the kecha wacha is vulnerable to shock traps in all three states.',
            'ash kecha wacha': 'the ash kecha wacha is vulnerable to shock traps in all three states.',
            'seltas queen': 'the seltas queen is vulnerable to shock traps in all three states.',
            'desert seltas queen': 'the desert seltas queen is vulnerable to shock traps in all three states.',
            'gore magala': 'the gore magala is vulnerable to shock traps in all three states.',
            'chaotic gore magala': 'the chaotic gore magala is vulnerable to shock traps in all three states.',
            'zamtrios': 'the zamtrios is vulnerable to shock traps in all three states.',
            'tigerstripe zamtrios': 'the tigerstripe zamtrios is vulnerable to shock traps in all three states.',
            'stygian zinogre': 'the stygian zinogre is vulnerable to shock traps in all three states.',
            'seregios': 'the seregios is vulnerable to shock traps in all three states.',
            'daimyo hermitaur': 'the daimyo hermitaur is vulnerable to shock traps in all three states.',
            'plum d.hermitaur': 'the plum d.hermitaur is vulnerable to shock traps in all three states.',
            'diablos': 'the diablos is vulnerable to shock traps in all three states.',
            'black diablos': 'the black diablos is vulnerable to shock traps in all three states.',
            'tigrex': 'the tigrex is vulnerable to shock traps in all three states.',
            'brute tigrex': 'the brute tigrex is vulnerable to shock traps in all three states.',
            'molten tigrex': 'the molten tigrex is vulnerable to shock traps in all three states.',
            'tetsucabra': 'the tetsucabra is vulnerable to shock traps in all three states.',
            'berserk tetsucabra': 'the berserk tetsucabra is vulnerable to shock traps in all three states.',
            'iodrome': 'the iodrome is vulnerable to shock traps in all three states.',
            'gendrome': 'the gendrome is vulnerable to shock traps in all three states.',
            'great jaggi': 'the great jaggi is vulnerable to shock traps in all three states.',
            'velocidrome': 'the velocidrome is vulnerable to shock traps in all three states.',
            'cephadrome': 'the cephadrome is vulnerable to shock traps in all three states.',
            'nerscylla': 'the nerscylla is vulnerable to shock traps in all three states.',
            'shrouded nerscylla': 'the shrouded nerscylla is vulnerable to shock traps in all three states.',
            'basarios': 'the basarios is vulnerable to shock traps in all three states.',
            'ruby basarios': 'the ruby basarios is vulnerable to shock traps in all three states.',
            'congalala': 'the congalala is vulnerable to shock traps in all three states.',
            'emerald congalala': 'the emerald congalala is vulnerable to shock traps in all three states.',
            'brachydios': 'the brachydios is vulnerable to shock traps in all three states.',
            'khezu': 'the khezu is vulnerable to shock traps in all three states.',
            'red khezu': 'the red khezu is vulnerable to shock traps in all three states.',
            'monoblos': 'the monoblos is vulnerable to shock traps in all three states.',
            'white monoblos': 'the white monoblos is vulnerable to shock traps in all three states.',
            'rajang': 'the rajang is vulnerable to shock traps in all three states.',
            'furious rajang': 'the furious rajang is vulnerable to shock traps in all three states.',
            'rathian': 'the rathian is vulnerable to shock traps in all three states.',
            'pink rathian': 'the pink rathian is vulnerable to shock traps in all three states.',
            'gold rathian': 'the gold rathian is vulnerable to shock traps in all three states.',
            'rathalos': 'the rathalos is vulnerable to shock traps in all three states.',
            'azure rathalos': 'the azure rathalos is vulnerable to shock traps in all three states.',
            'silver rathalos': 'the silver rathalos is vulnerable to shock traps in all three states.',
            'zinogre': 'in normal and fatigued state the zingore is vulnerable to shock traps, but not when enraged.',

    },
};
