/* eslint-disable  func-names */
/* eslint-disable max-len */
/* eslint quote-props: ['error', 'consistent']*/
module.exports = {
    'SONICBOMBS_EN_US': {
            'seltas': 'in normal, enraged and fatigued state the seltas is not vulnerable to sonic bombs.',
            'desert seltas': 'in normal, enraged and fatigued state the desert seltas is not vulnerable to sonic bombs.',
            'deviljho': 'in normal, enraged and fatigued state the deviljho is not vulnerable to sonic bombs.',
            'savage deviljho': 'in normal, enraged and fatigued state the savage deviljho is not vulnerable to sonic bombs.',
            'yian garuga': 'in normal, enraged and fatigued state the yian garuga is not vulnerable to sonic bombs.',
            'chameleos': 'in normal, enraged and fatigued state the chameleos is not vulnerable to sonic bombs.',
            'najarala': 'in normal, enraged and fatigued state the najarala is not vulnerable to sonic bombs.',
            'tidal najarala': 'in normal, enraged and fatigued state the tidal najarala is not vulnerable to sonic bombs.',
            'kirin': 'in normal, enraged and fatigued state the kirin is not vulnerable to sonic bombs.',
            'oroshi kirin': 'in normal, enraged and fatigued state the oroshi kirin is not vulnerable to sonic bombs.',
            'kushala daora': 'in normal, enraged and fatigued state the kushala daora is not vulnerable to sonic bombs.',
            'rusted kushala daora': 'in normal, enraged and fatigued state the rusted kushala daora is not vulnerable to sonic bombs.',
            'gravios': 'in normal, enraged and fatigued state the gravios is not vulnerable to sonic bombs.',
            'black gravios': 'in normal, enraged and fatigued state the black gravios is not vulnerable to sonic bombs.',
            'seltas queen': 'in normal, enraged and fatigued state the seltas queen is not vulnerable to sonic bombs.',
            'desert seltas queen': 'in normal, enraged and fatigued state the desert seltas queen is not vulnerable to sonic bombs.',
            'gypceros': 'in normal, enraged and fatigued state the gypceros is not vulnerable to sonic bombs.',
            'purple gypceros': 'in normal, enraged and fatigued state the purple gypceros is not vulnerable to sonic bombs.',
            'gore magala': 'in normal, enraged and fatigued state the gore magala is not vulnerable to sonic bombs.',
            'chaotic gore magala': 'in normal, enraged and fatigued state the chaotic gore magala is not vulnerable to sonic bombs.',
            'gogmazios': 'in normal, enraged and fatigued state the gogmazios is not vulnerable to sonic bombs.',
            'zamtrios': 'in normal, enraged and fatigued state the zamtrios is not vulnerable to sonic bombs.',
            'tigerstripe zamtrios': 'in normal, enraged and fatigued state the tigerstripe zamtrios is not vulnerable to sonic bombs.',
            'shagaru magala': 'in normal, enraged and fatigued state the shagaru magala is not vulnerable to sonic bombs.',
            'zinogre': 'in normal, enraged and fatigued state the zinogre is not vulnerable to sonic bombs.',
            'stygian zinogre': 'in normal, enraged and fatigued state the stygian zinogre is not vulnerable to sonic bombs.',
            'seregios': 'in normal, enraged and fatigued state the seregios is not vulnerable to sonic bombs.',
            'dalamadur': 'in normal, enraged and fatigued state the dalamadur is not vulnerable to sonic bombs.',
            'shah dalamadur': 'in normal, enraged and fatigued state the shah dalamadur is not vulnerable to sonic bombs.',
            'dah ren mohran': 'in normal, enraged and fatigued state the dah ren mohran is not vulnerable to sonic bombs.',
            'tigrex': 'in normal, enraged and fatigued state the tigrex is not vulnerable to sonic bombs.',
            'brute tigrex': 'in normal, enraged and fatigued state the brute tigrex is not vulnerable to sonic bombs.',
            'molten tigrex': 'in normal, enraged and fatigued state the molten tigrex is not vulnerable to sonic bombs.',
            'teostra': 'in normal, enraged and fatigued state the teostra is not vulnerable to sonic bombs.',
            'tetsucabra': 'in normal, enraged and fatigued state the tetsucabra is not vulnerable to sonic bombs.',
            'berserk tetsucabra': 'in normal, enraged and fatigued state the berserk tetsucabra is not vulnerable to sonic bombs.',
            'iodrome': 'in normal, enraged and fatigued state the iodrome is not vulnerable to sonic bombs.',
            'gendrome': 'in normal, enraged and fatigued state the gendrome is not vulnerable to sonic bombs.',
            'great jaggi': 'in normal, enraged and fatigued state the great jaggi is not vulnerable to sonic bombs.',
            'velocidrome': 'in normal, enraged and fatigued state the velocidrome is not vulnerable to sonic bombs.',
            'nerscylla': 'in normal, enraged and fatigued state the nerscylla is not vulnerable to sonic bombs.',
            'shrouded nerscylla': 'in normal, enraged and fatigued state the shrouded nerscylla is not vulnerable to sonic bombs.',
            'basarios': 'in normal, enraged and fatigued state the basarios is not vulnerable to sonic bombs.',
            'ruby basarios': 'in normal, enraged and fatigued state the ruby basarios is not vulnerable to sonic bombs.',
            'congalala': 'in normal, enraged and fatigued state the congalala is not vulnerable to sonic bombs.',
            'emerald congalala': 'in normal, enraged and fatigued state the emerald congalala is not vulnerable to sonic bombs.',
            'brachydios': 'in normal, enraged and fatigued state the brachydios is not vulnerable to sonic bombs.',
            'raging brachydios': 'in normal, enraged and fatigued state the raging brachydios is not vulnerable to sonic bombs.',
            'khezu': 'in normal, enraged and fatigued state the khezu is not vulnerable to sonic bombs.',
            'red khezu': 'in normal, enraged and fatigued state the red khezu is not vulnerable to sonic bombs.',
            'rajang': 'in normal, enraged and fatigued state the rajang is not vulnerable to sonic bombs.',
            'furious rajang': 'in normal, enraged and fatigued state the furious rajang is not vulnerable to sonic bombs.',
            'rathian': 'in normal, enraged and fatigued state the rathian is not vulnerable to sonic bombs.',
            'pink rathian': 'in normal, enraged and fatigued state the pink rathian is not vulnerable to sonic bombs.',
            'gold rathian': 'in normal, enraged and fatigued state the gold rathian is not vulnerable to sonic bombs.',
            'rathalos': 'in normal, enraged and fatigued state the rathalos is not vulnerable to sonic bombs.',
            'azure rathalos': 'in normal, enraged and fatigued state the azure rathalos is not vulnerable to sonic bombs.',
            'silver rathalos': 'in normal, enraged and fatigued state the silver rathalos is not vulnerable to sonic bombs.',
            'fatalis': 'in normal, enraged and fatigued state the fatalis is not vulnerable to sonic bombs.',
            'crimson fatalis': 'in normal, enraged and fatigued state the crimson fatalis is not vulnerable to sonic bombs.',
            'white fatalis': 'in normal, enraged and fatigued state the white fatalis is not vulnerable to sonic bombs.',
            'kecha wacha': 'the kecha wacha is  vulnerable to sonic bombs in all three states.',
            'ash kecha wacha': 'the ash kecha wacha is  vulnerable to sonic bombs in all three states.',
            'daimyo hermitaur': 'the daimyo hermitaur is  vulnerable to sonic bombs in all three states.',
            'plum d.hermitaur': 'the plum d.hermitaur is  vulnerable to sonic bombs in all three states.',
            'akantor': 'in normal and fatigued state the akantor is vulnerable to shock traps, but not when enraged.',
            'yian kut-ku': 'in normal and fatigued state the yian kut-ku is vulnerable to shock traps, but not when enraged.',
            'blue yian kut-ku': 'in normal and fatigued state the blue yian kut-ku is vulnerable to shock traps, but not when enraged.',
            'ukanlos': 'in normal and fatigued state the ukanlos is vulnerable to shock traps, but not when enraged.',
            'lagombi': 'in normal and fatigued state the lagombi is vulnerable to shock traps, but not when enraged.',
            'diablos': 'in normal and fatigued state the diablos is vulnerable to shock traps, but not when enraged.',
            'black diablos': 'in normal and fatigued state the black diablos is vulnerable to shock traps, but not when enraged.',
            'cephadrome': 'in normal and fatigued state the cephadrome is vulnerable to shock traps, but not when enraged.',
            'monoblos': 'in normal and fatigued state the monoblos is vulnerable to shock traps, but not when enraged.',
            'white monoblos': 'in normal and fatigued state the white monoblos is vulnerable to shock traps, but not when enraged.',

    },
};
